"use client";

import { ConversationProvider, useConversation } from "@elevenlabs/react";
import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { api, ApiError, type CallTurn, type LiveEvent } from "@/lib/api";
import { useLiveEvents } from "@/lib/use-live-events";
import { TurnTimeline } from "./turn-timeline";
import { Badge, Card, CardHeader, EmptyState, ErrorNote } from "./ui";
import { VoiceOrb } from "./voice-orb";

/** LiveKit logs this when ElevenLabs closes the call socket. The call has already ended. */
function isHangupSignalNoise(args: unknown[]): boolean {
  return args.some(
    (arg) => typeof arg === "string" && arg.includes("error reading from signal stream"),
  );
}

const SCENARIOS = [
  {
    title: "Policy questions (RAG)",
    prompts: [
      "What happens if I miss my bill due date?",
      "Which plan includes Netflix and Prime Video?",
      "Is 5G available in Pune?",
    ],
  },
  {
    title: "Account lookups (verify first)",
    prompts: [
      "Why is my bill higher this month? My number is 98765 43210, I'm Priya.",
      "How much data do I have left? It's 98123 45678, Rahul Verma.",
      "My service stopped working. 98111 22334, Arjun.",
    ],
  },
];

interface ElevenLabsMessage {
  id: string;
  role: "user" | "agent";
  message: string;
}

function VoiceDemoInner() {
  const [error, setError] = useState<string | null>(null);
  const [starting, setStarting] = useState(false);
  const [conversationId, setConversationId] = useState<string | null>(null);
  const [turns, setTurns] = useState<CallTurn[]>([]);
  const [fallback, setFallback] = useState<ElevenLabsMessage[]>([]);
  const [callId, setCallId] = useState<string | null>(null);
  const callIds = useRef(new Map<string, string>());

  useEffect(() => {
    const original = console.error.bind(console);
    console.error = ((...args: unknown[]) => {
      if (isHangupSignalNoise(args)) return;
      original(...args);
    }) as typeof console.error;
    return () => {
      console.error = original;
    };
  }, []);

  const conversation = useConversation({
    onConnect: ({ conversationId }) => {
      setConversationId(conversationId);
      const known = callIds.current.get(conversationId);
      if (known) setCallId(known);
    },
    onMessage: ({ message, role, event_id }) =>
      setFallback((prev) => [...prev, { id: `${role}-${event_id ?? prev.length}`, role, message }]),
    onError: (message) => setError(String(message)),
  });

  const status = conversation.status;
  const active = status === "connected";
  const connecting = starting || status === "connecting";

  useLiveEvents((event: LiveEvent) => {
    if (event.type === "call.started") {
      callIds.current.set(event.call.conversation_id, event.call.id);
      if (event.call.conversation_id === conversationId) setCallId(event.call.id);
    } else if (event.type === "call.turn" && event.call_id === callId) {
      setTurns((prev) => [...prev, event.turn]);
    }
  });

  async function toggle() {
    if (active) {
      conversation.endSession();
      return;
    }
    setError(null);
    setTurns([]);
    setFallback([]);
    setCallId(null);
    setStarting(true);
    try {
      await navigator.mediaDevices.getUserMedia({ audio: true });
      const session = await api<{ conversation_token: string }>("/api/voice/session");
      conversation.startSession({
        conversationToken: session.conversation_token,
        connectionType: "webrtc",
      });
    } catch (err) {
      if (err instanceof ApiError) setError(err.message);
      else if (err instanceof DOMException) setError("Microphone access is required to talk to Maya.");
      else setError("Could not reach the Vocal backend. Is it running on port 8000?");
    } finally {
      setStarting(false);
    }
  }

  const statusLabel = connecting
    ? "Connecting..."
    : active
      ? conversation.isSpeaking
        ? "Maya is speaking"
        : "Listening..."
      : "Tap to start a call";

  return (
    <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
      <div className="space-y-6">
        <Card className="flex flex-col items-center px-6 py-10">
          <VoiceOrb
            active={active}
            connecting={connecting}
            speaking={conversation.isSpeaking}
            getInputVolume={conversation.getInputVolume}
            getOutputVolume={conversation.getOutputVolume}
            onClick={toggle}
          />
          <p className="mt-4 text-sm font-medium">{statusLabel}</p>
          <p className="mt-1 max-w-sm text-center text-xs text-muted">
            Speech-to-text and text-to-speech run on ElevenLabs. Every reply is generated by the
            LangGraph agent on Groq, grounded in the Lauki knowledge base.
          </p>
          {error && (
            <div className="mt-5 w-full max-w-md">
              <ErrorNote error={error} />
            </div>
          )}
        </Card>

        <Card>
          <CardHeader
            title="Live transcript"
            description="Includes the agent's tool calls and the documents it retrieved."
            action={
              callId && (
                <Link
                  href={`/calls/${callId}`}
                  className="inline-flex items-center gap-1 text-xs text-violet-300 hover:underline"
                >
                  Open call <ExternalLink className="size-3" />
                </Link>
              )
            }
          />
          <div className="max-h-[480px] overflow-y-auto px-5 py-5">
            {turns.length > 0 ? (
              <TurnTimeline turns={turns} />
            ) : fallback.length > 0 ? (
              <div className="space-y-2 text-sm">
                {fallback.map((m) => (
                  <p key={m.id}>
                    <span className="text-muted">{m.role === "agent" ? "Maya" : "You"}: </span>
                    {m.message}
                  </p>
                ))}
              </div>
            ) : (
              <EmptyState>Start a call and ask Maya about plans, bills or coverage.</EmptyState>
            )}
          </div>
        </Card>
      </div>

      <div className="space-y-6">
        {SCENARIOS.map((group) => (
          <Card key={group.title}>
            <CardHeader title={group.title} />
            <ul className="space-y-2 px-5 py-4 text-sm">
              {group.prompts.map((prompt) => (
                <li key={prompt} className="rounded-lg bg-white/[0.03] px-3 py-2 text-foreground/85">
                  &ldquo;{prompt}&rdquo;
                </li>
              ))}
            </ul>
          </Card>
        ))}
        <Card className="px-5 py-4 text-xs leading-relaxed text-muted">
          <Badge tone="accent" className="mb-2">
            Tip
          </Badge>
          <p>
            Account tools only unlock after Maya verifies your registered number and name. See{" "}
            <Link href="/customers" className="text-violet-300 hover:underline">
              Customers
            </Link>{" "}
            for the demo accounts.
          </p>
        </Card>
      </div>
    </div>
  );
}

export function VoiceDemo() {
  return (
    <ConversationProvider>
      <VoiceDemoInner />
    </ConversationProvider>
  );
}
