"""Create or update the ElevenLabs agent that fronts Vocal, and optionally attach a Twilio number.

The agent uses ElevenLabs for speech-to-text, text-to-speech and turn-taking, and points its
"Custom LLM" at this backend's OpenAI-compatible endpoint so all reasoning runs in LangGraph.

Usage (from backend/):
    uv run python -m scripts.setup_elevenlabs_agent            # create or update the agent
    uv run python -m scripts.setup_elevenlabs_agent --twilio   # also import the Twilio number
"""

import argparse
import re
import sys
from typing import Any

import httpx

from app.config import REPO_ROOT, get_settings

API = "https://api.elevenlabs.io/v1"
AGENT_NAME = "Vocal - Lauki Phones support"
SECRET_NAME = "vocal_custom_llm_key"
FIRST_MESSAGE = "Hi, this is Maya from Lauki Phones customer care. How can I help you today?"

# ElevenLabs renders this prompt (including system dynamic variables) and sends it as the system
# message to our custom LLM; the backend parses the ids and builds the real prompt itself.
ELEVENLABS_PROMPT = """\
You are Maya, the Lauki Phones voice agent. Responses are generated by the Vocal backend.
conversation_id: {{system__conversation_id}}
caller_id: {{system__caller_id}}
"""


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def request(client: httpx.Client, method: str, path: str, **kwargs: Any) -> dict[str, Any]:
    response = client.request(method, f"{API}{path}", **kwargs)
    if response.status_code >= 400:
        fail(f"{method} {path} failed ({response.status_code}): {response.text[:500]}")
    return response.json() if response.content else {}


def ensure_secret(client: httpx.Client, value: str) -> str:
    secrets = request(client, "GET", "/convai/secrets").get("secrets", [])
    for secret in secrets:
        if secret.get("name") == SECRET_NAME:
            print(f"Reusing workspace secret '{SECRET_NAME}'")
            return secret["secret_id"]
    created = request(
        client, "POST", "/convai/secrets", json={"type": "new", "name": SECRET_NAME, "value": value}
    )
    print(f"Created workspace secret '{SECRET_NAME}'")
    return created["secret_id"]


def agent_payload(backend_url: str, secret_id: str, voice_id: str) -> dict[str, Any]:
    return {
        "name": AGENT_NAME,
        "tags": ["vocal", "portfolio"],
        "conversation_config": {
            "agent": {
                "first_message": FIRST_MESSAGE,
                "language": "en",
                "prompt": {
                    "prompt": ELEVENLABS_PROMPT,
                    "llm": "custom-llm",
                    "custom_llm": {
                        "url": f"{backend_url.rstrip('/')}/v1",
                        "model_id": "vocal-langgraph",
                        "api_key": {"secret_id": secret_id},
                    },
                    "built_in_tools": {
                        "end_call": {
                            "type": "system",
                            "name": "end_call",
                            "description": "",
                            "params": {"system_tool_type": "end_call"},
                        }
                    },
                },
            },
            "tts": {"voice_id": voice_id, "model_id": "eleven_flash_v2"},
        },
    }


def write_env(key: str, value: str) -> None:
    env_path = REPO_ROOT / ".env"
    if not env_path.exists():
        print(f"Add this to your .env: {key}={value}")
        return
    content = env_path.read_text()
    line = f"{key}={value}"
    if re.search(rf"^{key}=.*$", content, flags=re.M):
        content = re.sub(rf"^{key}=.*$", line, content, flags=re.M)
    else:
        content = content.rstrip("\n") + f"\n{line}\n"
    env_path.write_text(content)
    print(f"Saved {key} to .env")


def import_twilio_number(client: httpx.Client, agent_id: str) -> None:
    s = get_settings()
    if not (s.twilio_account_sid and s.twilio_auth_token and s.twilio_phone_number):
        fail("Set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN and TWILIO_PHONE_NUMBER to import a number")

    existing = request(client, "GET", "/convai/phone-numbers")
    numbers = existing if isinstance(existing, list) else existing.get("phone_numbers", [])
    for number in numbers:
        if number.get("phone_number") == s.twilio_phone_number:
            request(
                client,
                "PATCH",
                f"/convai/phone-numbers/{number['phone_number_id']}",
                json={"agent_id": agent_id},
            )
            print(f"Assigned existing number {s.twilio_phone_number} to the agent")
            return

    request(
        client,
        "POST",
        "/convai/phone-numbers",
        json={
            "provider": "twilio",
            "phone_number": s.twilio_phone_number,
            "label": "Vocal - Lauki support line",
            "sid": s.twilio_account_sid,
            "token": s.twilio_auth_token,
            "agent_id": agent_id,
            "enable_sms": False,
        },
    )
    print(f"Imported Twilio number {s.twilio_phone_number}; inbound calls now reach the agent")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("--twilio", action="store_true", help="Import/assign the Twilio number")
    args = parser.parse_args()

    s = get_settings()
    if not s.elevenlabs_api_key:
        fail("ELEVENLABS_API_KEY is not set")
    if not s.public_backend_url.startswith("https://"):
        fail("PUBLIC_BACKEND_URL must be the public https URL of the backend (e.g. ngrok)")
    if not s.custom_llm_api_key:
        fail("CUSTOM_LLM_API_KEY is not set (generate one with: openssl rand -hex 32)")

    with httpx.Client(headers={"xi-api-key": s.elevenlabs_api_key}, timeout=30) as client:
        secret_id = ensure_secret(client, s.custom_llm_api_key)
        payload = agent_payload(s.public_backend_url, secret_id, s.elevenlabs_voice_id)

        if s.elevenlabs_agent_id:
            request(client, "PATCH", f"/convai/agents/{s.elevenlabs_agent_id}", json=payload)
            agent_id = s.elevenlabs_agent_id
            print(f"Updated agent {agent_id}")
        else:
            agent_id = request(client, "POST", "/convai/agents/create", json=payload)["agent_id"]
            print(f"Created agent {agent_id}")
            write_env("ELEVENLABS_AGENT_ID", agent_id)

        if args.twilio:
            import_twilio_number(client, agent_id)

    print(
        "\nNext: in ElevenLabs > Agents > Settings > Webhooks, add a post-call webhook to\n"
        f"  {s.public_backend_url.rstrip('/')}/webhooks/elevenlabs/post-call\n"
        "and put its HMAC secret in ELEVENLABS_WEBHOOK_SECRET."
    )


if __name__ == "__main__":
    main()
