"use client";

import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { ChannelBadge, StatusBadge } from "@/components/call-badges";
import { TurnTimeline } from "@/components/turn-timeline";
import { Card, CardHeader, EmptyState, ErrorNote } from "@/components/ui";
import { api, type CallDetail } from "@/lib/api";
import { useLiveEvents } from "@/lib/use-live-events";
import { cn, formatDate, formatDuration, formatTime } from "@/lib/utils";

export default function CallDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [call, setCall] = useState<CallDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<"agent" | "transcript">("agent");

  const load = useCallback(async () => {
    try {
      setCall(await api<CallDetail>(`/api/calls/${id}`));
    } catch {
      setError("Call not found.");
    }
  }, [id]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- initial data fetch
    load();
  }, [load]);

  useLiveEvents((event) => {
    if (event.type === "call.turn" && event.call_id === id) {
      setCall((prev) => (prev ? { ...prev, turns: [...prev.turns, event.turn] } : prev));
    } else if (event.type !== "call.turn" && event.call.id === id) {
      load();
    }
  });

  if (error) return <ErrorNote error={error} />;
  if (!call) return null;

  const details: [string, string][] = [
    ["Customer", call.customer_name ?? "Not verified"],
    ["Caller", call.caller_number ?? "Browser session"],
    ["Started", `${formatDate(call.started_at)}, ${formatTime(call.started_at)}`],
    ["Duration", formatDuration(call.duration_seconds)],
    ["Conversation ID", call.conversation_id],
  ];
  const termination = call.call_metadata?.termination_reason;
  if (typeof termination === "string") details.push(["Ended because", termination]);

  return (
    <>
      <Link
        href="/calls"
        className="mb-4 inline-flex items-center gap-1.5 text-sm text-muted hover:text-foreground"
      >
        <ArrowLeft className="size-4" /> All calls
      </Link>

      <div className="mb-6 flex flex-wrap items-center gap-3">
        <h1 className="text-xl font-semibold tracking-tight">
          {call.customer_name ?? "Unverified caller"}
        </h1>
        <ChannelBadge channel={call.channel} />
        <StatusBadge call={call} />
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_300px]">
        <Card>
          <div className="flex gap-1 border-b border-panel-border px-3 pt-3">
            {(
              [
                ["agent", "Agent trace"],
                ["transcript", "ElevenLabs transcript"],
              ] as const
            ).map(([key, label]) => (
              <button
                key={key}
                onClick={() => setTab(key)}
                className={cn(
                  "rounded-t-lg px-3 py-2 text-sm",
                  tab === key ? "bg-white/5 text-foreground" : "text-muted hover:text-foreground",
                )}
              >
                {label}
              </button>
            ))}
          </div>
          <div className="px-5 py-5">
            {tab === "agent" ? (
              call.turns.length ? (
                <TurnTimeline turns={call.turns} />
              ) : (
                <EmptyState>No agent turns were logged for this call.</EmptyState>
              )
            ) : call.transcript?.length ? (
              <div className="space-y-3 text-sm">
                {call.transcript.map((line, i) => (
                  <div key={i} className="flex gap-3">
                    <span className="w-12 shrink-0 font-mono text-xs text-muted">
                      {formatDuration(line.time_in_call_secs)}
                    </span>
                    <span className="w-12 shrink-0 text-xs text-muted">
                      {line.role === "agent" ? "Maya" : "Caller"}
                    </span>
                    <p>{line.message}</p>
                  </div>
                ))}
              </div>
            ) : (
              <EmptyState>
                The full transcript arrives from ElevenLabs&apos; post-call webhook once the call
                ends.
              </EmptyState>
            )}
          </div>
        </Card>

        <div className="space-y-6">
          {call.summary && (
            <Card>
              <CardHeader title="Summary" description="Generated by ElevenLabs post-call analysis" />
              <p className="px-5 py-4 text-sm leading-relaxed text-foreground/85">{call.summary}</p>
            </Card>
          )}
          <Card>
            <CardHeader title="Details" />
            <dl className="space-y-3 px-5 py-4 text-sm">
              {details.map(([label, value]) => (
                <div key={label}>
                  <dt className="text-xs text-muted">{label}</dt>
                  <dd className="break-all">{value}</dd>
                </div>
              ))}
            </dl>
          </Card>
        </div>
      </div>
    </>
  );
}
