"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 08:05:33.056026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('plan',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_type', sa.Enum('prepaid', 'postpaid', name='connectiontype', native_enum=False, length=16), nullable=False),
    sa.Column('price_inr', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('data_mb', sa.Integer(), nullable=False),
    sa.Column('voice_minutes', sa.Integer(), nullable=False),
    sa.Column('sms', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_status', sa.Enum('active', 'suspended', 'expired', name='accountstatus', native_enum=False, length=16), nullable=False),
    sa.Column('activated_on', sa.Date(), nullable=False),
    sa.Column('bill_cycle_day', sa.Integer(), nullable=True),
    sa.Column('validity_ends_on', sa.Date(), nullable=True),
    sa.Column('autopay_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plan.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_table('bill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_inr', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('paid', 'unpaid', 'overdue', name='billstatus', native_enum=False, length=16), nullable=False),
    sa.Column('line_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_customer_id'), 'bill', ['customer_id'], unique=False)
    op.create_table('call',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('channel', sa.Enum('phone', 'web', name='callchannel', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', name='callstatus', native_enum=False, length=16), nullable=False),
    sa.Column('caller_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('transcript', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('call_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_conversation_id'), 'call', ['conversation_id'], unique=True)
    op.create_table('usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('data_used_mb', sa.Integer(), nullable=False),
    sa.Column('voice_used_minutes', sa.Integer(), nullable=False),
    sa.Column('sms_used', sa.Integer(), nullable=False),
    sa.Column('rollover_data_mb', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_customer_id'), 'usage', ['customer_id'], unique=False)
    op.create_table('call_turn',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('tool_args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_turn_call_id'), 'call_turn', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_turn_call_id'), table_name='call_turn')
    op.drop_table('call_turn')
    op.drop_index(op.f('ix_usage_customer_id'), table_name='usage')
    op.drop_table('usage')
    op.drop_index(op.f('ix_call_conversation_id'), table_name='call')
    op.drop_table('call')
    op.drop_index(op.f('ix_bill_customer_id'), table_name='bill')
    op.drop_table('bill')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('plan')
    op.drop_table('knowledge_document')
    # ### end Alembic commands ###
